# Generated by Django 4.1.5 on 2023-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=35)),
                ('cust_address', models.CharField(max_length=37)),
                ('cust_phone', models.IntegerField()),
            ],
        ),
    ]
